import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageJsonPath = path.join(__dirname, "../package.json");

const filePath = path.join(__dirname, "../date.js");

const readFiles = async () => {
  try {
    const autoGeneratedFileData = await fs.promises.readFile(
      "./date.js",
      "utf8"
    );
    const dateMatch = autoGeneratedFileData.match(/const date = "(.*?)"/);

    const packageJsonData = await fs.promises.readFile(packageJsonPath, "utf8");
    const packageJson = JSON.parse(packageJsonData);

    if (dateMatch && dateMatch[1]) {
      console.log(
        `${packageJson.name}@${packageJson.version} was automatically generated on:`,
        dateMatch[1]
      );
    }
  } catch (err) {
    console.error("An error occurred while reading the files:", err);
    process.exit(1);
  }
};

readFiles();
